# Generated by Django 4.0 on 2022-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tournament_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='one_player',
        ),
        migrations.AlterField(
            model_name='info',
            name='links',
            field=models.ManyToManyField(to='main.SocialMedia'),
        ),
        migrations.AlterField(
            model_name='photogalerie',
            name='images',
            field=models.ManyToManyField(to='main.PhotoGaleryImage'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='main.Team'),
        ),
    ]
