# Generated by Django 4.0 on 2022-07-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_group_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
