# Generated by Django 4.0 on 2022-07-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_team_is_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='team',
            field=models.ManyToManyField(to='main.Team'),
        ),
    ]
