# Generated by Django 4.0 on 2022-07-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tournament_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
